import { makeStyles } from '@material-ui/core';

export default makeStyles((theme) => ({
  root: {
    display: 'flex',
    alignItems: 'center',
    minHeight: '5em',
    justifyContent: 'center',
    '& p': {
      fontSize: '2em',
      textDecoration: 'none',
      color: '#bdc3c7',
      position: 'relative',
      MozTransitionProperty: 'all',
      OTransitionProperty: 'all',
      WebkitTransitionProperty: 'all',
      transitionProperty: 'all',
      MozTransitionDuration: '0.5s',
      OTransitionDuration: '0.5s',
      WebkitTransitionDuration: '0.5s',
      transitionDuration: '0.5s',
      MozTransitionTimingFunction: 'ease-in-out',
      OTransitionTimingFunction: 'ease-in-out',
      WebkitTransitionTimingFunction: 'ease-in-out',
      transitionTimingFunction: 'ease-in-out',
      '&:hover': {
        color: 'white',
      },
      '&:before': {
        position: 'absolute',
        top: '51%',
        overflow: 'hidden',
        width: '40%',
        height: 4,
        content: '',
        backgroundColor: '#1abc9c',
        marginLeft: '-45%',
        textAlign: 'right',
        MozBorderRadius: '5px / 5px',
        WebkitBorderRadius: '5px 5px',
        borderRadius: '5px / 5px',
        MozTransitionProperty: 'all',
        OTransitionProperty: 'all',
        WebkitTransitionProperty: 'all',
        transitionProperty: 'all',
        MozTransitionDuration: '0.5s',
        OTransitionDuration: '0.5s',
        WebkitTransitionDuration: '0.5s',
        transitionDuration: '0.5s',
        MozTransitionTimingFunction: 'ease-in-out',
        OTransitionTimingFunction: 'ease-in-out',
        WebkitTransitionTimingFunction: 'ease-in-out',
        transitionTimingFunction: 'ease-in-out',
      },
      '&:hover:before': {
        width: '70%',
        marginLeft: '-75%',
        backgroundColor: '#55e7ca',
      },
    },
  },
}));
